// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/catalogs/modalities": {
            "get": {
                "description": "Returns all modalities ordered by modality_id ascending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogs"
                ],
                "summary": "List modalities",
                "responses": {
                    "200": {
                        "description": "List of modalities",
                        "schema": {
                            "$ref": "#/definitions/catalogs.ListModalitiesResult"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalogs/property-types": {
            "get": {
                "description": "Returns all non-deprecated property types ordered by property_type_id ascending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogs"
                ],
                "summary": "List property types",
                "responses": {
                    "200": {
                        "description": "List of property types",
                        "schema": {
                            "$ref": "#/definitions/catalogs.ListPropertyTypesResult"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalogs/rent-periods": {
            "get": {
                "description": "Returns all rent periods ordered by period_id ascending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogs"
                ],
                "summary": "List rent periods",
                "responses": {
                    "200": {
                        "description": "List of rent periods",
                        "schema": {
                            "$ref": "#/definitions/catalogs.ListRentPeriodsResult"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payment-methods": {
            "get": {
                "description": "List supported payment methods (Card, PayPal, OXXO, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Get available payment methods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/payments.PaymentMethodResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments": {
            "get": {
                "description": "History of payments for the authenticated user. Requires X-User-ID header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "List user payments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/payments.PaymentResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments/intent": {
            "post": {
                "description": "Start a payment process for a property reservation (Apartado). Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Create a payment intent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payment Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payments.PaymentIntentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/payments.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments/{uuid}/confirm": {
            "post": {
                "description": "Simulate the confirmation of a payment from a gateway. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Confirm a payment (Mock)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Mock Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payments.ConfirmPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/payments.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/properties/{id}/availability": {
            "get": {
                "description": "Get available 1-hour slots for a property on a specific date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Get property availability",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Property ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD). Defaults to today.",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/visits.TimeSlot"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/uploads/properties/{property_uuid}/photos": {
            "post": {
                "description": "Uploads a photo for a property to R2 and registers it",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Upload property photo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "property_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "The image file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Label",
                        "name": "label",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Alt Text",
                        "name": "alt_text",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Sort Order",
                        "name": "sort_order",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Is Cover",
                        "name": "is_cover",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/uploads.UploadPhotoResult"
                        }
                    }
                }
            }
        },
        "/visits": {
            "get": {
                "description": "List visits according to user role (Admin, Agent, Client). Supports filtering by status, property and date. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "List user visits",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Status ID",
                        "name": "status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Property ID",
                        "name": "property_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/visits.VisitResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new visit request in 'Pending' status. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Schedule a visit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Visit Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/visits.CreateVisitRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/visits.VisitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/visits/{uuid}/complete": {
            "patch": {
                "description": "Mark a confirmed visit as completed. Only for Agents or Admin. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Complete a visit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/visits/{uuid}/confirm": {
            "patch": {
                "description": "Transition a visit status towards 'Confirmed' by Client or Agent. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Confirm a visit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/visits/{uuid}/reschedule": {
            "patch": {
                "description": "Cancels the old visit and creates a new one with the new date. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Reschedule a visit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Old Visit UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New Visit Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/visits.CreateVisitRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/visits.VisitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "catalogs.ListModalitiesResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogs.Modality"
                    }
                }
            }
        },
        "catalogs.ListPropertyTypesResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogs.PropertyType"
                    }
                }
            }
        },
        "catalogs.ListRentPeriodsResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogs.RentPeriod"
                    }
                }
            }
        },
        "catalogs.Modality": {
            "type": "object",
            "properties": {
                "modality_id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Rent"
                }
            }
        },
        "catalogs.PropertyType": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string",
                    "example": "/icons/apartment.svg"
                },
                "name": {
                    "type": "string",
                    "example": "Apartment"
                },
                "property_type_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "catalogs.RentPeriod": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Monthly"
                },
                "period_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "payments.ConfirmPaymentRequest": {
            "type": "object",
            "required": [
                "mock_token"
            ],
            "properties": {
                "mock_token": {
                    "description": "e.g., \"tok_success\", \"tok_oxxo_pending\"",
                    "type": "string"
                }
            }
        },
        "payments.PaymentIntentRequest": {
            "type": "object",
            "required": [
                "amount",
                "method_id",
                "property_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "method_id": {
                    "type": "integer"
                },
                "property_id": {
                    "type": "integer"
                }
            }
        },
        "payments.PaymentMethodResponse": {
            "type": "object",
            "properties": {
                "method_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "payments.PaymentResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "payment_date": {
                    "type": "string"
                },
                "payment_uuid": {
                    "type": "string"
                },
                "property_id": {
                    "type": "integer"
                },
                "property_title": {
                    "type": "string"
                },
                "redirect_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "shared.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "message": {
                    "type": "string",
                    "example": "Resource not found"
                }
            }
        },
        "uploads.UploadPhotoResult": {
            "type": "object",
            "properties": {
                "photo_id": {
                    "type": "integer"
                },
                "storage_key": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "visits.CreateVisitRequest": {
            "type": "object",
            "required": [
                "property_id",
                "visit_date"
            ],
            "properties": {
                "property_id": {
                    "type": "integer"
                },
                "visit_date": {
                    "type": "string"
                }
            }
        },
        "visits.TimeSlot": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "end_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "visits.VisitResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "agent_id": {
                    "type": "integer"
                },
                "agent_name": {
                    "type": "string"
                },
                "agent_phone": {
                    "type": "string"
                },
                "city_name": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "client_phone": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "property_id": {
                    "type": "integer"
                },
                "property_title": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "visit_date": {
                    "type": "string"
                },
                "visit_uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Spazio API",
	Description:      "API de Spazio Backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
