// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/catalogs/modalities": {
            "get": {
                "description": "Returns all modalities ordered by modality_id ascending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogs"
                ],
                "summary": "List modalities",
                "responses": {
                    "200": {
                        "description": "List of modalities",
                        "schema": {
                            "$ref": "#/definitions/catalogs.ListModalitiesResult"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/api/v1/catalogs/orientations": {
=======
        "/catalogs/orientations": {
>>>>>>> 4920b6b (feat(catalogs): add orientations endpoint and related database schema)
            "get": {
                "description": "Returns all orientations ordered by name ascending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogs"
                ],
                "summary": "List orientations",
                "responses": {
                    "200": {
                        "description": "List of orientations",
                        "schema": {
                            "$ref": "#/definitions/catalogs.ListOrientationsResult"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/api/v1/catalogs/property-types": {
=======
        "/catalogs/property-types": {
>>>>>>> 4920b6b (feat(catalogs): add orientations endpoint and related database schema)
            "get": {
                "description": "Returns all non-deprecated property types ordered by property_type_id ascending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogs"
                ],
                "summary": "List property types",
                "responses": {
                    "200": {
                        "description": "List of property types",
                        "schema": {
                            "$ref": "#/definitions/catalogs.ListPropertyTypesResult"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/catalogs/rent-periods": {
            "get": {
                "description": "Returns rent periods enabled for the provided property type, ordered by period_id ascending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogs"
                ],
                "summary": "List rent periods",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Property type ID",
                        "name": "property_type_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of rent periods",
                        "schema": {
                            "$ref": "#/definitions/catalogs.ListRentPeriodsResult"
                        }
                    },
                    "400": {
                        "description": "Invalid query params",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/clauses": {
            "get": {
                "description": "Returns clauses available for the provided modality. When q is present, the endpoint performs a filtered search. Results are paginated.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clauses"
                ],
                "summary": "List clauses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Modality ID",
                        "name": "modality_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Results per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of clauses",
                        "schema": {
                            "$ref": "#/definitions/clauses.ListClausesResult"
                        }
                    },
                    "400": {
                        "description": "Invalid query params",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/properties": {
            "post": {
                "description": "Registers a property and all related records in a single database transaction. The backend generates the property UUID and stores subtype, location, pricing, services, and clauses atomically.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Register a new property",
                "parameters": [
                    {
                        "description": "Property payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/properties.CreatePropertyInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Property created",
                        "schema": {
                            "$ref": "#/definitions/properties.CreatePropertyResult"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/properties/{id}/availability": {
            "get": {
                "description": "Get available 1-hour slots for a property on a specific date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Get property availability",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Property ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD). Defaults to today.",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/visits.TimeSlot"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/services": {
            "get": {
                "description": "Returns popular active services when q is empty, or matching active services when q is provided. Results include metadata and honor the optional limit parameter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "List services",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of services",
                        "schema": {
                            "$ref": "#/definitions/services.ListServicesResult"
                        }
                    },
                    "400": {
                        "description": "Invalid query params",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uploads/properties/{property_uuid}/photos": {
            "post": {
                "description": "Uploads a photo for a property to R2 and registers it",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Upload property photo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Property UUID",
                        "name": "property_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "The image file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Label",
                        "name": "label",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Alt Text",
                        "name": "alt_text",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Sort Order",
                        "name": "sort_order",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Is Cover",
                        "name": "is_cover",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/uploads.UploadPhotoResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/visits": {
            "get": {
                "description": "List visits according to user role (Admin, Agent, Client). Supports filtering by status, property and date. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "List user visits",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Status ID",
                        "name": "status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Property ID",
                        "name": "property_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/visits.VisitResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new visit request in 'Pending' status. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Schedule a visit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Visit Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/visits.CreateVisitRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/visits.VisitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/visits/{uuid}/complete": {
            "patch": {
                "description": "Mark a confirmed visit as completed. Only for Agents or Admin. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Complete a visit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/visits/{uuid}/confirm": {
            "patch": {
                "description": "Transition a visit status towards 'Confirmed' by Client or Agent. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Confirm a visit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Visit UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/visits/{uuid}/reschedule": {
            "patch": {
                "description": "Cancels the old visit and creates a new one with the new date. Requires X-User-ID header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visits"
                ],
                "summary": "Reschedule a visit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Old Visit UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New Visit Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/visits.CreateVisitRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/visits.VisitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/shared.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "catalogs.ListModalitiesResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogs.Modality"
                    }
                }
            }
        },
        "catalogs.ListOrientationsResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogs.Orientation"
                    }
                }
            }
        },
        "catalogs.ListPropertyTypesResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogs.PropertyType"
                    }
                }
            }
        },
        "catalogs.ListRentPeriodsResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalogs.RentPeriod"
                    }
                }
            }
        },
        "catalogs.Modality": {
            "type": "object",
            "properties": {
                "modality_id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Rent"
                }
            }
        },
        "catalogs.Orientation": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "North"
                },
                "orientation_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "catalogs.PropertyType": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string",
                    "example": "/icons/apartment.svg"
                },
                "name": {
                    "type": "string",
                    "example": "Apartment"
                },
                "property_type_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "catalogs.RentPeriod": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Monthly"
                },
                "period_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "clauses.Clause": {
            "type": "object",
            "properties": {
                "clause_id": {
                    "type": "integer",
                    "example": 1
                },
                "code": {
                    "type": "string",
                    "example": "pets_allowed"
                },
                "sort_order": {
                    "type": "integer",
                    "example": 10
                },
                "value_type": {
                    "$ref": "#/definitions/clauses.ClauseValueType"
                }
            }
        },
        "clauses.ClauseValueType": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "boolean"
                }
            }
        },
        "clauses.ListClausesMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "clauses.ListClausesResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/clauses.Clause"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/clauses.ListClausesMeta"
                }
            }
        },
        "properties.CreateCommercialInput": {
            "type": "object",
            "properties": {
                "ceiling_height": {
                    "type": "number",
                    "example": 4.5
                },
                "internal_offices": {
                    "type": "integer",
                    "example": 2
                },
                "land_use": {
                    "type": "string",
                    "example": "Retail"
                },
                "loading_docks": {
                    "type": "integer",
                    "example": 1
                },
                "three_phase_power": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "properties.CreateLocationInput": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "integer",
                    "example": 1
                },
                "exterior_number": {
                    "type": "string",
                    "example": "45"
                },
                "interior_number": {
                    "type": "string",
                    "example": "A"
                },
                "is_public_address": {
                    "type": "boolean",
                    "example": true
                },
                "latitude": {
                    "type": "number",
                    "example": 19.5438
                },
                "longitude": {
                    "type": "number",
                    "example": -96.9102
                },
                "neighborhood": {
                    "type": "string",
                    "example": "Centro"
                },
                "postal_code": {
                    "type": "string",
                    "example": "91000"
                },
                "street": {
                    "type": "string",
                    "example": "Av. Principal"
                }
            }
        },
        "properties.CreatePropertyClauseInput": {
            "type": "object",
            "properties": {
                "boolean_value": {
                    "type": "boolean",
                    "example": true
                },
                "clause_id": {
                    "type": "integer",
                    "example": 1
                },
                "integer_value": {
                    "type": "integer",
                    "example": 2
                },
                "max_value": {
                    "type": "number",
                    "example": 3
                },
                "min_value": {
                    "type": "number",
                    "example": 1
                }
            }
        },
        "properties.CreatePropertyInput": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "residential"
                },
                "clauses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/properties.CreatePropertyClauseInput"
                    }
                },
                "commercial": {
                    "$ref": "#/definitions/properties.CreateCommercialInput"
                },
                "description": {
                    "type": "string",
                    "example": "Spacious residential property near downtown"
                },
                "is_featured": {
                    "type": "boolean",
                    "example": false
                },
                "location": {
                    "$ref": "#/definitions/properties.CreateLocationInput"
                },
                "lot_area": {
                    "type": "number",
                    "example": 200
                },
                "modality_id": {
                    "type": "integer",
                    "example": 1
                },
                "owner_id": {
                    "type": "integer",
                    "example": 1
                },
                "property_type_id": {
                    "type": "integer",
                    "example": 1
                },
                "rent_prices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/properties.CreateRentPriceInput"
                    }
                },
                "residential": {
                    "$ref": "#/definitions/properties.CreateResidentialInput"
                },
                "sale_price": {
                    "$ref": "#/definitions/properties.CreateSalePriceInput"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        3,
                        7
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Casa en Xalapa"
                }
            }
        },
        "properties.CreatePropertyResult": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/properties.CreatePropertyResultData"
                }
            }
        },
        "properties.CreatePropertyResultData": {
            "type": "object",
            "properties": {
                "property_uuid": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "properties.CreateRentPriceInput": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "MXN"
                },
                "deposit": {
                    "type": "number",
                    "example": 16000
                },
                "is_negotiable": {
                    "type": "boolean",
                    "example": false
                },
                "period_id": {
                    "type": "integer",
                    "example": 3
                },
                "rent_price": {
                    "type": "number",
                    "example": 8000
                }
            }
        },
        "properties.CreateResidentialInput": {
            "type": "object",
            "properties": {
                "bathrooms": {
                    "type": "integer",
                    "example": 2
                },
                "bedrooms": {
                    "type": "integer",
                    "example": 3
                },
                "beds": {
                    "type": "integer",
                    "example": 4
                },
                "built_area": {
                    "type": "number",
                    "example": 120
                },
                "construction_year": {
                    "type": "integer",
                    "example": 2010
                },
                "floors": {
                    "type": "integer",
                    "example": 2
                },
                "is_furnished": {
                    "type": "boolean",
                    "example": false
                },
                "orientation_id": {
                    "type": "integer",
                    "example": 2
                },
                "parking_spots": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "properties.CreateSalePriceInput": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "MXN"
                },
                "is_negotiable": {
                    "type": "boolean",
                    "example": true
                },
                "sale_price": {
                    "type": "number",
                    "example": 1500000
                }
            }
        },
        "services.ListServicesMeta": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                },
                "shown": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "services.ListServicesResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.Service"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/services.ListServicesMeta"
                }
            }
        },
        "services.Service": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string",
                    "example": "basic"
                },
                "code": {
                    "type": "string",
                    "example": "wifi"
                },
                "icon": {
                    "type": "string",
                    "example": "wifi"
                },
                "service_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "shared.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "message": {
                    "type": "string",
                    "example": "Resource not found"
                }
            }
        },
        "uploads.UploadPhotoResult": {
            "type": "object",
            "properties": {
                "photo_id": {
                    "type": "integer"
                },
                "storage_key": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "visits.CreateVisitRequest": {
            "type": "object",
            "required": [
                "property_id",
                "visit_date"
            ],
            "properties": {
                "property_id": {
                    "type": "integer"
                },
                "visit_date": {
                    "type": "string"
                }
            }
        },
        "visits.TimeSlot": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "end_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "visits.VisitResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "agent_id": {
                    "type": "integer"
                },
                "agent_name": {
                    "type": "string"
                },
                "agent_phone": {
                    "type": "string"
                },
                "city_name": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "client_phone": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "property_id": {
                    "type": "integer"
                },
                "property_title": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "visit_date": {
                    "type": "string"
                },
                "visit_uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Spazio API",
	Description:      "API de Spazio Backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
