basePath: /
definitions:
  catalogs.ListModalitiesResult:
    properties:
      data:
        items:
          $ref: '#/definitions/catalogs.Modality'
        type: array
    type: object
  catalogs.ListPropertyTypesResult:
    properties:
      data:
        items:
          $ref: '#/definitions/catalogs.PropertyType'
        type: array
    type: object
  catalogs.ListRentPeriodsResult:
    properties:
      data:
        items:
          $ref: '#/definitions/catalogs.RentPeriod'
        type: array
    type: object
  catalogs.Modality:
    properties:
      modality_id:
        example: 1
        type: integer
      name:
        example: Rent
        type: string
    type: object
  catalogs.PropertyType:
    properties:
      icon:
        example: /icons/apartment.svg
        type: string
      name:
        example: Apartment
        type: string
      property_type_id:
        example: 1
        type: integer
    type: object
  catalogs.RentPeriod:
    properties:
      name:
        example: Monthly
        type: string
      period_id:
        example: 1
        type: integer
    type: object
  shared.ErrorResponse:
    properties:
      code:
        example: 404
        type: integer
      message:
        example: Resource not found
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API de Spazio Backend
  title: Spazio API
  version: "1.0"
paths:
  /catalogs/modalities:
    get:
      description: Returns all modalities ordered by modality_id ascending.
      produces:
      - application/json
      responses:
        "200":
          description: List of modalities
          schema:
            $ref: '#/definitions/catalogs.ListModalitiesResult'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: List modalities
      tags:
      - Catalogs
  /catalogs/property-types:
    get:
      description: Returns all non-deprecated property types ordered by property_type_id
        ascending.
      produces:
      - application/json
      responses:
        "200":
          description: List of property types
          schema:
            $ref: '#/definitions/catalogs.ListPropertyTypesResult'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: List property types
      tags:
      - Catalogs
  /catalogs/rent-periods:
    get:
      description: Returns all rent periods ordered by period_id ascending.
      produces:
      - application/json
      responses:
        "200":
          description: List of rent periods
          schema:
            $ref: '#/definitions/catalogs.ListRentPeriodsResult'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/shared.ErrorResponse'
      summary: List rent periods
      tags:
      - Catalogs
swagger: "2.0"
